version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    depends_on:
      - server
      - guide1
      - guide2
    environment:
      WOW_SERVER: "server:29170"
      WOW_GUIDES: "guide1:29171,guide2:29172"
      WOW_RETRY_COUNT: 5
      WOW_REQUEST_INTERVAL: 5s
      WOW_DEBUG: "true"

  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    expose:
      - 29170
    environment:
      WOW_HOST: "server"
      WOW_PORT: "29170"
      WOW_MULTICORE: "true"
      WOW_TIMEOUT: 5s
      WOW_GUIDE_SECRETS: "some-secret-for-guide-1,some-secret-for-guide-2"
      WOW_SECRET_LENGTH: 20
      WOW_SECRET_UPDATE_INTERVAL: 10s
      WOW_TOUR_LENGTH: 5
      WOW_DEBUG: "true"

  guide1:
    build:
      context: .
      dockerfile: docker/guide.Dockerfile
    expose:
      - 29171
    environment:
      WOW_HOST: "guide1"
      WOW_PORT: "29171"
      WOW_MULTICORE: "true"
      WOW_TIMEOUT: 5s
      WOW_SECRET: "some-secret-for-guide-1"
      WOW_DEBUG: "true"

  guide2:
    build:
      context: .
      dockerfile: docker/guide.Dockerfile
    expose:
      - 29172
    environment:
      WOW_HOST: "guide2"
      WOW_PORT: "29172"
      WOW_MULTICORE: "true"
      WOW_TIMEOUT: 5s
      WOW_SECRET: "some-secret-for-guide-2"
      WOW_DEBUG: "true"
