package guide

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *RequestMsg) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "PreviousHash":
			err = dc.ReadExactBytes((z.PreviousHash)[:])
			if err != nil {
				err = msgp.WrapError(err, "PreviousHash")
				return
			}
		case "TourNumber":
			z.TourNumber, err = dc.ReadByte()
			if err != nil {
				err = msgp.WrapError(err, "TourNumber")
				return
			}
		case "TourLength":
			z.TourLength, err = dc.ReadByte()
			if err != nil {
				err = msgp.WrapError(err, "TourLength")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *RequestMsg) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "PreviousHash"
	err = en.Append(0x83, 0xac, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x48, 0x61, 0x73, 0x68)
	if err != nil {
		return
	}
	err = en.WriteBytes((z.PreviousHash)[:])
	if err != nil {
		err = msgp.WrapError(err, "PreviousHash")
		return
	}
	// write "TourNumber"
	err = en.Append(0xaa, 0x54, 0x6f, 0x75, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteByte(z.TourNumber)
	if err != nil {
		err = msgp.WrapError(err, "TourNumber")
		return
	}
	// write "TourLength"
	err = en.Append(0xaa, 0x54, 0x6f, 0x75, 0x72, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68)
	if err != nil {
		return
	}
	err = en.WriteByte(z.TourLength)
	if err != nil {
		err = msgp.WrapError(err, "TourLength")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *RequestMsg) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "PreviousHash"
	o = append(o, 0x83, 0xac, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x48, 0x61, 0x73, 0x68)
	o = msgp.AppendBytes(o, (z.PreviousHash)[:])
	// string "TourNumber"
	o = append(o, 0xaa, 0x54, 0x6f, 0x75, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72)
	o = msgp.AppendByte(o, z.TourNumber)
	// string "TourLength"
	o = append(o, 0xaa, 0x54, 0x6f, 0x75, 0x72, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68)
	o = msgp.AppendByte(o, z.TourLength)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *RequestMsg) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "PreviousHash":
			bts, err = msgp.ReadExactBytes(bts, (z.PreviousHash)[:])
			if err != nil {
				err = msgp.WrapError(err, "PreviousHash")
				return
			}
		case "TourNumber":
			z.TourNumber, bts, err = msgp.ReadByteBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TourNumber")
				return
			}
		case "TourLength":
			z.TourLength, bts, err = msgp.ReadByteBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TourLength")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *RequestMsg) Msgsize() (s int) {
	s = 1 + 13 + msgp.ArrayHeaderSize + (32 * (msgp.ByteSize)) + 11 + msgp.ByteSize + 11 + msgp.ByteSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ResponseMsg) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Hash":
			err = dc.ReadExactBytes((z.Hash)[:])
			if err != nil {
				err = msgp.WrapError(err, "Hash")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ResponseMsg) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "Hash"
	err = en.Append(0x81, 0xa4, 0x48, 0x61, 0x73, 0x68)
	if err != nil {
		return
	}
	err = en.WriteBytes((z.Hash)[:])
	if err != nil {
		err = msgp.WrapError(err, "Hash")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ResponseMsg) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "Hash"
	o = append(o, 0x81, 0xa4, 0x48, 0x61, 0x73, 0x68)
	o = msgp.AppendBytes(o, (z.Hash)[:])
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ResponseMsg) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Hash":
			bts, err = msgp.ReadExactBytes(bts, (z.Hash)[:])
			if err != nil {
				err = msgp.WrapError(err, "Hash")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ResponseMsg) Msgsize() (s int) {
	s = 1 + 5 + msgp.ArrayHeaderSize + (32 * (msgp.ByteSize))
	return
}
