// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// QuoteRepository is an autogenerated mock type for the quoteRepository type
type QuoteRepository struct {
	mock.Mock
}

type QuoteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *QuoteRepository) EXPECT() *QuoteRepository_Expecter {
	return &QuoteRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields:
func (_m *QuoteRepository) Get() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// QuoteRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type QuoteRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *QuoteRepository_Expecter) Get() *QuoteRepository_Get_Call {
	return &QuoteRepository_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *QuoteRepository_Get_Call) Run(run func()) *QuoteRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QuoteRepository_Get_Call) Return(_a0 string) *QuoteRepository_Get_Call {
	_c.Call.Return(_a0)
	return _c
}
