// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	guide "github.com/itimky/word-of-wisom/api/guide"
	mock "github.com/stretchr/testify/mock"

	server "github.com/itimky/word-of-wisom/api/server"
)

// TcpClient is an autogenerated mock type for the tcpClient type
type TcpClient struct {
	mock.Mock
}

type TcpClient_Expecter struct {
	mock *mock.Mock
}

func (_m *TcpClient) EXPECT() *TcpClient_Expecter {
	return &TcpClient_Expecter{mock: &_m.Mock}
}

// RequestGuideByIdx provides a mock function with given fields: idx, request
func (_m *TcpClient) RequestGuideByIdx(idx int, request guide.RequestMsg) (*guide.ResponseMsg, error) {
	ret := _m.Called(idx, request)

	var r0 *guide.ResponseMsg
	if rf, ok := ret.Get(0).(func(int, guide.RequestMsg) *guide.ResponseMsg); ok {
		r0 = rf(idx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*guide.ResponseMsg)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, guide.RequestMsg) error); ok {
		r1 = rf(idx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TcpClient_RequestGuideByIdx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestGuideByIdx'
type TcpClient_RequestGuideByIdx_Call struct {
	*mock.Call
}

// RequestGuideByIdx is a helper method to define mock.On call
//  - idx int
//  - request guide.RequestMsg
func (_e *TcpClient_Expecter) RequestGuideByIdx(idx interface{}, request interface{}) *TcpClient_RequestGuideByIdx_Call {
	return &TcpClient_RequestGuideByIdx_Call{Call: _e.mock.On("RequestGuideByIdx", idx, request)}
}

func (_c *TcpClient_RequestGuideByIdx_Call) Run(run func(idx int, request guide.RequestMsg)) *TcpClient_RequestGuideByIdx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(guide.RequestMsg))
	})
	return _c
}

func (_c *TcpClient_RequestGuideByIdx_Call) Return(_a0 *guide.ResponseMsg, _a1 error) *TcpClient_RequestGuideByIdx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// RequestServer provides a mock function with given fields: request
func (_m *TcpClient) RequestServer(request server.RequestMsg) (*server.ResponseMsg, error) {
	ret := _m.Called(request)

	var r0 *server.ResponseMsg
	if rf, ok := ret.Get(0).(func(server.RequestMsg) *server.ResponseMsg); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*server.ResponseMsg)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(server.RequestMsg) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TcpClient_RequestServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestServer'
type TcpClient_RequestServer_Call struct {
	*mock.Call
}

// RequestServer is a helper method to define mock.On call
//  - request server.RequestMsg
func (_e *TcpClient_Expecter) RequestServer(request interface{}) *TcpClient_RequestServer_Call {
	return &TcpClient_RequestServer_Call{Call: _e.mock.On("RequestServer", request)}
}

func (_c *TcpClient_RequestServer_Call) Run(run func(request server.RequestMsg)) *TcpClient_RequestServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(server.RequestMsg))
	})
	return _c
}

func (_c *TcpClient_RequestServer_Call) Return(_a0 *server.ResponseMsg, _a1 error) *TcpClient_RequestServer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}
